# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/fleur/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),fleur)

$(call add-radio-file-sha1-checked,radio/audio_dsp.img,4ab8c6165102478e20eee25a90687d3775fec0f9)
$(call add-radio-file-sha1-checked,radio/gz.img,0127894adc4b5cea79c1eb23f5dc58d71443440a)
$(call add-radio-file-sha1-checked,radio/lk.img,6e429575bde60759f6e942506cfbcc0063a968a6)
$(call add-radio-file-sha1-checked,radio/logo.img,8a91d6937db78242171562e067dd54e30f90d02b)
$(call add-radio-file-sha1-checked,radio/md1img.img,b1735f5721e369d0ebe6e6202437cb4edf37fdd0)
$(call add-radio-file-sha1-checked,radio/pi_img.img,2e163273fff39b6ec04683d531a6f71aa98f34cc)
$(call add-radio-file-sha1-checked,radio/preloader_raw.img,f767654388634e2edc037ee3de29e8c2c1b03d86)
$(call add-radio-file-sha1-checked,radio/scp.img,3bdfd639decdaee2698c9b17068ada53174970fc)
$(call add-radio-file-sha1-checked,radio/spmfw.img,a34809ffc0e2693d897377cea501bb9c28498e8d)
$(call add-radio-file-sha1-checked,radio/sspm.img,bd2fc52fb66e4094b138110d0bea114bfff54dd3)
$(call add-radio-file-sha1-checked,radio/tee.img,f5657136ed4db9c0eb740e3766a291670efe9feb)

endif
